app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('logout', array('uses'=>'UsersController@logout','as'=>'logout'));
Route::get('/', ['uses'=>'HomeController@home','as'=>'home']);
Route::resource('sessions', 'SessionsController');
Route::get('returns/create', array('uses'=>'PropertyController@create','as'=>'returns.create'));
Route::resource('dashboard','DashboardController');
Route::get('property/examine/{id}',['uses'=>'PropertyController@examine','as'=>'property.examine']);
Route::post('property.finalize',['uses'=>'PropertyController@finalize','as'=>'property.finalize']);
Route::resource('property','PropertyController');
Route::resource('users','UsersController'); 
Route::resource('departments','DepartmentController'); 
Route::post('login', array('uses'=>'UsersController@login','as'=>'login'));
Route::get('users/{id}/changepassword', array('uses'=>'UsersController@changePassword','as'=>'users.changepassword'));
Route::put('users/{id}/updateprofile', array('uses'=>'UsersController@updateProfile','as'=>'users.updateprofile'));
Route::get('users/{id}/profile', array('uses'=>'UsersController@profile','as'=>'users.profile'));
Route::get('property/{id}/otp', array('uses'=>'PropertyController@otp','as'=>'property.otp'));
Route::get('forgotpassword', ['uses'=>'UsersController@forgotpassword','as'=>'forgotpassword']);
Route::post('submitforgot', ['uses'=>'UsersController@submitforgot','as'=>'submitforgot']);
Route::post('property/notify',['uses'=>'PropertyController@notify','as'=>'property.notify']);
//Route::get('otp', function(){ dd('Hello'); });
Route::get('getemployeelist', ['uses'=>'DepartmentController@getemployeelist','as'=>'getemployeelist']);
Route::get('getreturns', ['uses'=>'PropertyController@getreturns','as'=>'getreturns']);
Route::get('pendingreturns',['uses'=>'PropertyController@pendingreturns','as'=>'pendingreturns']);

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

	public function property(){
		return $this->hasOne('Property');
	}

}

app/controllers/UsersController.php
<?php

class UsersController extends \BaseController {

	public function __construct()
	{
		$this->beforeFilter('auth',['except'=>['login','forgotpassword','submitforgot']]);
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		if(Auth::user()->user_type == 'admin') {
			$userType = array('employee'=>'employee');
		} elseif(Auth::user()->user_type == 'superadmin') {
			$userType = array('','superadmin'=>'superadmin','admin'=>'admin','employee'=>'employee');
		}
		$departments	= Department::orderby('name')->lists('name','id');
		$userAll = User::orderBy('name')->paginate();
		$index = $userAll->getPerPage() * ($userAll->getCurrentPage()-1) + 1;
		
		if(Auth::user()->user_type == 'employee'){
			return Redirect::to('/')->with(['flash_message'=>'You are not authorized to view the page']);
		}
		else
		return View::make('users.index')->with(array(
										'userAll'	=> $userAll,
										'userType'	=> $userType,
										'index'		=> $index,
										'departments' => $departments
										));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		if(Auth::user()->user_type == 'employee'){
			return Redirect::to('/')->with(['flash_message'=>'You are not authorized to view the page']);
		}
		else
		return View::make('users.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$user = new User();
		$credentials = array(
				'username' 	=> 'required|unique:'.$user->getTable().',username',
				'emp_id' 	=> 'required|unique:'.$user->getTable().',emp_id',
				'mobile' 	=> 'required|unique:'.$user->getTable().',mobile',
				'password'	=> 'required'
				);
		$validator	= Validator::make(Input::all(),$credentials);
		if($validator->fails()){
			return Redirect::to('users')
								->withErrors($validator)
								->withInput(Input::all())
								->with(['flash_message'=>'Username, Employee ID, Mobile should be unique']);
		} else {
			$user = new User();
			$user->emp_id 			= Input::get('emp_id');
			$user->name 			= Input::get('name');
			$user->mobile 			= Input::get('mobile');
			$user->username 		= Input::get('username');
			$user->password 		= Hash::make(Input::get('password'));
			$user->user_type 		= Input::get('user_type');
			$user->email 			= Input::get('email');
			$user->department_id 	= Input::get('department_id');
			$user->entry_into_service	= Input::get('entry_into_service');
			$user->superannuation_date	= Input::get('superannuation_date');
			$user->remember_token 	= Input::get('_token');
			if($user->save())

			return Redirect::back()->with(['flash_message'=>'User successfully created']);
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{	
		if(Auth::user()->user_type == 'admin') {
			$userType = array('employee'=>'employee');
		} elseif(Auth::user()->user_type == 'superadmin') {
			$userType = array('','superadmin'=>'superadmin','admin'=>'admin','employee'=>'employee');
		}
		$departments	= Department::orderby('name')->lists('name','id');
		$userAll = User::orderBy('name')->paginate();
		$index = $userAll->getPerPage() * ($userAll->getCurrentPage()-1) + 1;
		$userById = User::find($id);
		if(Auth::user()->user_type == 'employee'){
			return Redirect::to('/')->with(['flash_message'=>'You are not authorized to view the page']);
		}
		else
		return View::make('users.edit')->with(array(
										'userById'	=> $userById,
										'userAll'	=> $userAll,
										'userType'	=> $userType,
										'index'		=> $index,
										'departments' => $departments
										));
		// return View::make('users.edit');	
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$user = new User;

		$rules = array(
			'username' => 'required|unique:' . $user->getTable() . ',username,' . $id,
			'emp_id' => 'required|unique:' . $user->getTable() . ',emp_id,' . $id,
			'mobile' => 'required|unique:' . $user->getTable() . ',mobile,' . $id
			);

		$validator = Validator::make(Input::all(), $rules);

		if($validator->fails()){
			return Redirect::route('users.edit', $id)
				->withErrors($validator)
				->withInput(Input::all())
				->with(['flash_message'=>'Username, Employee ID, Mobile already exist']);
		} else {
			$user = User::find($id);
			$user->emp_id 			= Input::get('emp_id');
			$user->name 			= Input::get('name');
			$user->mobile 			= Input::get('mobile');
			$user->username 		= Input::get('username');
			if(strlen(Input::get('password')) > 0)
				$user->password 	= Hash::make(Input::get('password'));
			$user->email 			= Input::get('email');
			$user->user_type 		= Input::get('user_type');
			$user->department_id	= Input::get('department_id');
			$user->entry_into_service	= Input::get('entry_into_service');
			$user->superannuation_date	= Input::get('superannuation_date');
			if($user->save())
				return Redirect::back()->with(['flash_message'=>'User successfully Updated']);
			else
				return Redirect::back()->with(['flash_message'=>'Error on Update'])->withInput();
		}


	
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		User::destroy($id);
		return Redirect::route('users.index');
	}

	public function login(){
		$attempt = Auth::attempt([
				'username' => Input::get('username'),
				'password' => Input::get('password')
			]);

		if ($attempt) {
			if(Auth::user()->user_type == 'employee')
				return Redirect::route('property.create');
			else 
				return Redirect::route('dashboard.index');
		}
		else
			return Redirect::to('/')->with(['flash_message'=>'Invalid Username or Password'])->withInput();
	}

	public function logout(){
		Auth::logout();
		return Redirect::to('/');
	}

	/*public function changePassword($id){
		$userById = User::find($id);
		return View::make('users.changepassword')->with(array('userById'=>$userById));
	}*/

	public function profile($id)
	{	
		if(Auth::user()->id == $id){
			$userById = User::find($id);
			return View::make('users.profile')->with(array(
											'userById'	=> $userById
											));	
		} else {
			return Redirect::to('/')->with(['flash_message'=>'You Are Not Authorized']);
		}
	}

	public function updateProfile($id){

		$user = new User;

		$rules = array(
			'username' => 'required|unique:' . $user->getTable() . ',username,' . $id,
			'emp_id' => 'required|unique:' . $user->getTable() . ',emp_id,' . $id,
			'mobile' => 'required|unique:' . $user->getTable() . ',mobile,' . $id
			);

		$validator = Validator::make(Input::all(), $rules);

		if($validator->fails()){
			return Redirect::route('users.updateprofile', $id)
				->withErrors($validator)
				->withInput(Input::all())
				->with(['flash_message'=>'Username, Employee ID, Mobile already exist']);
		} else {
			$user = User::find($id);
			$user->emp_id 			= Input::get('emp_id');
			$user->name 			= Input::get('name');
			$user->mobile 			= Input::get('mobile');
			$user->username 		= Input::get('username');
			if(strlen(Input::get('password')) > 0)
				$user->password 	= Hash::make(Input::get('password'));
			$user->email 			= Input::get('email');
			$user->entry_into_service	= Input::get('entry_into_service');
			$user->superannuation_date	= Input::get('superannuation_date');
			if($user->save())
				return Redirect::back()->with(['flash_message'=>'User successfully Updated']);
			else
				return Redirect::back()->with(['flash_message'=>'Error on Update'])->withInput();
		}

	}

	public function forgotpassword(){
		return View::make('users.forgotpassword');
	}

	public function submitforgot(){
		$username = Input::get('username');
		$pass = rand(1000,9999);
		$mobile = Input::get('mobile');

		$userId = User::where('username','=',$username)
						->where('mobile','=',$mobile)
						->pluck('id');
		if($userId) {
			include("../app/config/local/sms.php");
			$post = curl_init();
			curl_setopt($post, CURLOPT_URL, "$url/sendsms?uname=".$user."&pwd=".$password."&senderid=".$sender."&to=".$mobile."&msg=".urlencode("Your temporary password is $pass. Change it on your next login.")."&route=T");
			//curl_setopt($post, CURLOPT_URL, "$url/sendsms?uname=".urlencode($user)."&pwd=".urlencode($pass)."&senderid=".urlencode($sender)."&to=".$phone."&msg=".urlencode("One Time Password for submitting Property Returns form is $otp.")."&route=T");
			curl_exec($post);
			curl_close($post);

			$user = User::find($userId);
			$user->password = Hash::make($pass);
			$user->save();



			return Redirect::back()->with(['flash_message'=>'Password Successfully Reset And New Password is Send to Your Mobile'])->withInput();	
		} else {
			return Redirect::back()->with(['flash_message'=>'Username and Mobile No is not Match.'])->withInput();	
		}
	}



}

app/views/users/changepassword.blade.php
@extends('layout')

@section('container')

<section id="view">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Change Password</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                <!-- <form name="sentMessage" id="contactForm" novalidate> -->
                {{ Form::model($userById,array('url'=>route('users.updatepassword',$userById->id),'method'=>'put','class'=>'')) }}
                    <div class="row control-group">
                        <div class="form-group col-xs-12  controls">
                           	<label>Current Password</label>
                            {{Form::password('currentpassword',['class'=>'form-control','placeholder'=>'Current Password','id'=>'currentpassword','size'=>'10','data-validation-required-message'=>'Please enter Current Password.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12  controls">
                            <label>New Password</label>
                            {{Form::password('password',['class'=>'form-control','placeholder'=>'New Password','id'=>'newpassword','size'=>'10','data-validation-required-message'=>'Please enter New Password.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12  controls">
                            <label>Confirm New Password</label>
                            {{Form::password('password_confirm',['class'=>'form-control','placeholder'=>'Confirm New Password','id'=>'newpassword','size'=>'10','data-validation-required-message'=>'Please enter Confirm New Password.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-success btn-lg">Send</button>
                        </div>
                    </div>
                {{Form::close()}}
                <!-- </form> -->
            </div>
        </div>
    </div>
</section>

@stop

app/views/users/create.blade.php
@extends('layout')

@section('container')

<section id="view">
    <div class="container">
        <div class="row" id= "createuser-row">
            <div class="col-lg-12 text-center">
                <h2>Add User</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                <!-- <form name="sentMessage" id="contactForm" novalidate> -->
                {{Form::open(['route'=>'users.store','class'=>''])}}
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Employee ID</label>
                            {{Form::text('emp_id','',['class'=>'form-control','placeholder'=>'Employee ID','id'=>'emp_id','size'=>'10','data-validation-required-message'=>'Please enter Employee ID.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                           	<label>Name</label>
                            {{Form::text('name','',['class'=>'form-control','placeholder'=>'Name','id'=>'name','size'=>'10','data-validation-required-message'=>'Please enter Name.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Username</label>
                            {{Form::text('username','',['class'=>'form-control','placeholder'=>'Username','id'=>'username','size'=>'10','data-validation-required-message'=>'Please enter Username.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Password</label>
                            {{Form::password('password',['class'=>'form-control','placeholder'=>'Password','id'=>'password','size'=>'10','data-validation-required-message'=>'Please enter Password.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Mobile</label>
                            {{Form::text('mobile','',['class'=>'form-control','placeholder'=>'Mobile','id'=>'mobile','size'=>'10','data-validation-required-message'=>'Please enter Mobile.','maxlength'=>'10','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Entry Into Service</label>
                            {{Form::text('entry_into_service','',['class'=>'form-control','placeholder'=>'Entry Into Service','id'=>'entry_into_service','size'=>'10','data-validation-required-message'=>'Please enter Entry Into Service.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Superannuation Date</label>
                            {{Form::text('superannuation_date','',['class'=>'form-control','placeholder'=>'Superannuation Date','id'=>'superannuation_date','size'=>'10','data-validation-required-message'=>'Please enter Supperannuation Date.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>User Type</label>
                            {{Form::select('user_type',array('superadmin','admin','employee'),'',['class'=>'form-control','placeholder'=>'User Type','id'=>'user_type','size'=>'10','data-validation-required-message'=>'Please enter User Type.','required'])}}
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-success btn-lg">Send</button>
                        </div>
                    </div>
                {{Form::close()}}
                <!-- </form> -->
            </div>
        </div>
    </div>
</section>

@stop

app/views/users/edit.blade.php
@extends('layout')

@section('container')

<section id="view">
    <div class="container" style="margin-top:20px">
        <div class="col-md-8">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>List Users</h3>
                    <!-- <hr class="star-primary"> -->
                </div>
            </div>
            <div class="row" >
                
                <div class="table-responsive">
                        <table class="table table-hover table-striped table-bordered">
                            <thead>
                                <tr id='returnstr'>
                                    <th>#</th>
                                    <th>Employee ID</th>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Mobile</th>
                                    <th>Entry Into Service</th>
                                    <th>Superannuation Date</th>
                                    <th>User Type</th>
                                    <th colspan="2">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $slno = 0; ?>
                                @foreach($userAll as $user)
                                <tr>
                                    <td>{{$index+$slno}}</td>
                                    <td>{{$user->emp_id}}</td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->username}}</td>
                                    <td>{{$user->mobile}}</td>
                                    <td>{{$user->entry_into_service}}</td>
                                    <td>{{$user->superannuation_date}}</td>
                                    <td>{{$user->user_type}}</td>
                                        {{Form::open(array('url'=>route('users.destroy', array($user->id)),'method'=>'delete'))}}
                                    <td>
                                            <a href="{{route('users.edit', array($user->id))}}" class="btn btn-xs btn-success tooltip-top" title="Edit User"><i class="glyphicon glyphicon-edit"></i></a>&nbsp;&nbsp;
                                    </td>
                                    <td>
                                            <button type="submit" onclick="return confirm ('<?php echo _('Are you sure') ?>');" name="id" class="btn btn-xs btn-danger tooltip-top" title="Remove User" value="{{$user->id}}"><i class="glyphicon glyphicon-trash"></i></button>
                                        {{Form::close()}}
                                    </td>
                                </tr>
                                <?php $slno++; ?>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="10"> {{ $userAll->links() }}</td>
                                </tr>
                            </tfoot>
                        </table>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>Edit User</h3>
                    <!-- <hr class="star-primary"> -->
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                    <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                    <!-- <form name="sentMessage" id="contactForm" novalidate> -->
                    {{ Form::model($userById,array('url'=>route('users.update',$userById->id),'method'=>'put','class'=>'')) }}
                        <div class="row control-group">
                            <div class="form-group col-xs-12 controls">
                                <label>Departments</label>
                                {{Form::select('department_id',$departments,$userById->department_id,['class'=>'form-control','placeholder'=>'Departments','id'=>'department_id','data-validation-required-message'=>'Please Select Departments.','required'])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 controls">
                                <label>User Type</label>
                                {{Form::select('user_type',$userType,$userById->user_type,['class'=>'form-control','placeholder'=>'User Type','id'=>'user_type','data-validation-required-message'=>'Please enter User Type.','required'])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 controls">
                                <label>Employee ID</label>
                                {{Form::text('emp_id',null,['class'=>'form-control','placeholder'=>'Employee ID','id'=>'emp_id','size'=>'10','data-validation-required-message'=>'Please enter Employee ID.','required'])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12  controls">
                                <label>Name</label>
                                {{Form::text('name',null,['class'=>'form-control','placeholder'=>'Name','id'=>'name','size'=>'10','data-validation-required-message'=>'Please enter Name.','required'])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12  controls">
                                <label>Username</label>
                                <?php if(Auth::user()->user_type == 'superadmin') { $usertype = ""; } else { $usertype = "readonly"; } ?>
                                {{Form::text('username',null,['class'=>'form-control','placeholder'=>'Username','id'=>'username','size'=>'10','data-validation-required-message'=>'Please enter Username.', $usertype])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 controls">
                                <label>Password</label>
                                {{Form::password('password',['class'=>'form-control','placeholder'=>'Password','id'=>'password','size'=>'10','data-validation-required-message'=>'Please enter Password.'])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12  controls">
                                <label>Mobile</label>
                                {{Form::text('mobile',null,['class'=>'form-control','placeholder'=>'Mobile','id'=>'mobile','size'=>'10','data-validation-required-message'=>'Please enter Mobile.','maxlength'=>'10','required'])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12  controls">
                                <label>Email</label>
                                {{Form::text('email',null,['class'=>'form-control','placeholder'=>'Email','id'=>'email','size'=>'10','data-validation-required-message'=>'Please enter Email.','required'])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12  controls">
                                <label>Entry Into Service</label>
                                <div class="input-group">    
                                    {{Form::text('entry_into_service',null,['class'=>'form-control','placeholder'=>'Entry Into Service','id'=>'datetimepicker1','size'=>'10','data-validation-required-message'=>'Please enter Entry Into Service.','required'])}}
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                </div>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12  controls">
                                <label>Superannuation Date</label>
                                <div class="input-group">    
                                    {{ Form::text('superannuation_date',null, ['class'=>'form-control','id'=>'datetimepicker2','required','placeholder'=>'Superannuation Date','required']) }}
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                </div>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <button type="submit" class="btn btn-success btn-md">Update</button>
                            </div>
                        </div>
                    {{Form::close()}}
                    <!-- </form> -->
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $('#datetimepicker1').datetimepicker({
        step: 5
    });

    $('#datetimepicker2').datetimepicker({
        step: 5
    });
</script>

@stop