app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('logout', array('uses'=>'UsersController@logout','as'=>'logout'));
Route::get('/', ['uses'=>'HomeController@home','as'=>'home']);
Route::resource('sessions', 'SessionsController');
Route::get('returns/create', array('uses'=>'PropertyController@create','as'=>'returns.create'));
Route::resource('dashboard','DashboardController');
Route::get('property/examine/{id}',['uses'=>'PropertyController@examine','as'=>'property.examine']);
Route::post('property.finalize',['uses'=>'PropertyController@finalize','as'=>'property.finalize']);
Route::resource('property','PropertyController');
Route::resource('users','UsersController'); 
Route::resource('departments','DepartmentController'); 
Route::post('login', array('uses'=>'UsersController@login','as'=>'login'));
Route::get('users/{id}/changepassword', array('uses'=>'UsersController@changePassword','as'=>'users.changepassword'));
Route::put('users/{id}/updateprofile', array('uses'=>'UsersController@updateProfile','as'=>'users.updateprofile'));
Route::get('users/{id}/profile', array('uses'=>'UsersController@profile','as'=>'users.profile'));
Route::get('property/{id}/otp', array('uses'=>'PropertyController@otp','as'=>'property.otp'));
Route::get('forgotpassword', ['uses'=>'UsersController@forgotpassword','as'=>'forgotpassword']);
Route::post('submitforgot', ['uses'=>'UsersController@submitforgot','as'=>'submitforgot']);
Route::post('property/notify',['uses'=>'PropertyController@notify','as'=>'property.notify']);
//Route::get('otp', function(){ dd('Hello'); });
Route::get('getemployeelist', ['uses'=>'DepartmentController@getemployeelist','as'=>'getemployeelist']);
Route::get('getreturns', ['uses'=>'PropertyController@getreturns','as'=>'getreturns']);
Route::get('pendingreturns',['uses'=>'PropertyController@pendingreturns','as'=>'pendingreturns']);

app/models/Department.php
<?php

class Department extends Eloquent {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'departments';


	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */

}

app/controllers/DepartmentController.php
<?php

class DepartmentController extends \BaseController {

	public function __construct()
	{
		$this->beforeFilter('auth',['except'=>'getemployeelist']);
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$departmentAll = Department::orderBy('name')->paginate();
		$index = $departmentAll->getPerPage() * ($departmentAll->getCurrentPage()-1) + 1;
		if(Auth::user()->user_type == 'employee'){
			return Redirect::to('/')->with(['flash_message'=>'<div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>You are not authorized to view the page</div>']);
		}
		else
		return View::make('departments.index')->with(array(
										'departmentAll'	=> $departmentAll,
										'index'		=> $index
										));
	}


	public function getemployeelist()
	{
		$employees = User::where('department_id','=',Input::get('dept_id'))->where('user_type','=','employee')->get();
		return Response::json($employees);
	}
	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//return View::make('departments.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$department = new Department();
		$department->name 				= Input::get('name');
		if($department->save())
			return Redirect::back()->with(['flash_message'=>'Department successfully created','msgtype'=>'success']);
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{	
		$departmentAll = Department::orderBy('name')->paginate();
		$index = $departmentAll->getPerPage() * ($departmentAll->getCurrentPage()-1) + 1;
		$departmentById = Department::find($id);
		if(Auth::user()->user_type == 'employee'){
			return Redirect::to('/')->with(['flash_message'=>'<div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>You are not authorized to view the page</div>']);
		}
		else
		return View::make('departments.edit')->with(array(
										'departmentById'	=> $departmentById,
										'departmentAll'	=> $departmentAll,
										'index'		=> $index
										));
		// return View::make('departments.edit');	
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$department = Department::find($id);
		$department->name 	= Input::get('name');
		if($department->save())
			return Redirect::back()->with(['flash_message'=>'Department successfully Updated','msgtype'=>'success']);
		
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Department::destroy($id);
		return Redirect::route('departments.index');
	}


}

app/views/departments/edit.blade.php
@extends('layout')

@section('container')

<section id="view">
    <div class="container" style="margin-top:20px">
        <div class="col-md-8">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>List Departments</h3>
                    <!-- <hr class="star-primary"> -->
                </div>
            </div>
            <div class="row" >
                
                <div class="table-responsive">
                        <table class="table table-hover table-striped table-bordered">
                            <thead>
                                <tr id='returnstr'>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th colspan="2">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $slno = 0; ?>
                                @foreach($departmentAll as $department)
                                <tr>
                                    <td align="center" class="col-md-1">{{$index+$slno}}</td>
                                    <td class="col-md-8">{{$department->name}}</td>
                                        {{Form::open(array('url'=>route('departments.destroy', array($department->id)),'method'=>'delete'))}}
                                    <td>
                                            <a href="{{route('departments.edit', array($department->id))}}" class="btn btn-xs btn-success tooltip-top" title="Edit department"><i class="glyphicon glyphicon-edit"></i></a>&nbsp;&nbsp;
                                    </td>
                                    <td>
                                            <button type="submit" onclick="return confirm ('<?php echo _('Are you sure') ?>');" name="id" class="btn btn-xs btn-danger tooltip-top" title="Remove department" value="{{$department->id}}"><i class="glyphicon glyphicon-trash"></i></button>
                                        {{Form::close()}}
                                    </td>
                                </tr>
                                <?php $slno++; ?>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="10"> {{ $departmentAll->links() }}</td>
                                </tr>
                            </tfoot>
                        </table>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>Edit Department</h3>
                    <!-- <hr class="star-primary"> -->
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                    <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                    <!-- <form name="sentMessage" id="contactForm" novalidate> -->
                    {{ Form::model($departmentById,array('url'=>route('departments.update',$departmentById->id),'method'=>'put','class'=>'')) }}
                        
                        <div class="row control-group">
                            <div class="form-group col-xs-12  controls">
                                <label>Name</label>
                                {{Form::text('name',null,['class'=>'form-control','placeholder'=>'Name','id'=>'name','size'=>'10','data-validation-required-message'=>'Please enter Name.','required'])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <button type="submit" class="btn btn-success btn-md">Update</button>
                            </div>
                        </div>
                    {{Form::close()}}
                    <!-- </form> -->
                </div>
            </div>
        </div>
    </div>
</section>

@stop

app/views/departments/index.blade.php
@extends('layout')

@section('container')

<section id="view">
    <div class="container" style="margin-top:20px">
        <div class="col-md-8">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>List Departments</h3>
                    <!-- <hr class="star-primary"> -->
                </div>
            </div>
            <div class="row" >
                <div class="table-responsive">
                        <table class="table table-hover table-striped table-bordered">
                            <thead>
                                <tr id='returnstr'>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th colspan="2">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $slno = 0; ?>
                                @foreach($departmentAll as $department)
                                <tr>
                                    <td align="center" class="col-md-1">{{$index+$slno}}</td>
                                    <td class="col-md-8">{{$department->name}}</td>
                                        {{Form::open(array('url'=>route('departments.destroy', array($department->id)),'method'=>'delete'))}}
                                    <td>
                                            <a href="{{route('departments.edit', array($department->id))}}" class="btn btn-xs btn-success tooltip-top" title="Edit department"><i class="glyphicon glyphicon-edit"></i></a>&nbsp;&nbsp;
                                    </td>
                                    <td>
                                            <button type="submit" onclick="return confirm ('<?php echo _('Are you sure') ?>');" name="id" class="btn btn-xs btn-danger tooltip-top" title="Remove department" value="{{$department->id}}"><i class="glyphicon glyphicon-trash"></i></button>
                                        {{Form::close()}}
                                    </td>
                                </tr>
                                <?php $slno++; ?>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="4"> {{ $departmentAll->links() }}</td>
                                </tr>
                            </tfoot>
                        </table>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>Add department</h3>
                    <!-- <hr class="star-primary"> -->
                </div>
            </div>
            <div class="row" style="font-size:12px">
                <div class="col-lg-12">
                    <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                    <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                    <!-- <form name="sentMessage" id="contactForm" novalidate> -->
                    {{Form::open(['route'=>'departments.store','class'=>''])}}
                       
                        
                        <div class="row control-group">
                            <div class="form-group col-xs-12 controls">
                                <label>Name</label>
                                {{Form::text('name','',['class'=>'form-control','placeholder'=>'Name','id'=>'name','size'=>'10','data-validation-required-message'=>'Please enter Name.','required'])}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <button type="submit" class="btn btn-success btn-md">Add Department</button>
                            </div>
                        </div>
                    {{Form::close()}}
                    <!-- </form> -->
                </div>
            </div>
        </div>
    </div>
</section>

@stop